# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config

name: "dp speedtest"
description: >-
  Measure internet connection performance metrics with Speedtest CLI
url: https://github.com/diablodale/dp-ha-addons/tree/main/dp-speedtest
version: "0.1.45"
homeassistant: 2025.3.4
stage: experimental
slug: dp-speedtest  # appended to create actual slug in HA server db, e.g. local_dp-speedtest, 5c53de3b_esphome
panel_icon: mdi:speedometer
# panel_title:

# fyi current addon container is Alpine Linux v3.21 yet their addon template uses alpine v3.15 ghcr.io/home-assistant/amd64-base:3.15
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
#image: "ghcr.io/diablodale/{arch}-dp-speedtest"
init: false
#watchdog: ???

# permissions
homeassistant_api: true # access home assistant REST api proxy at `http://supervisor/core/api` (subset of full supervisor api) and ws://supervisor/core/websocket (will always fail auth without this perm)
# only hassio_role=manager could run `bashio::addons` to get slugs for all addons
# roles default and homeassistant worked for specifics like `bashio::addon.name` since they call `http://supervisor/addons/self/info`
#hassio_api: true # allows a range of supervisor api access
#hassio_role: manager


# TODO create services like a python http server?
#startup: services
#ports:
#  8000/tcp: 8000
#map:
#  - homeassistant_config:rw
#  - share:rw
#tmpfs: true

schema:
  accept_eula: bool
  accept_privacy: bool
  interval: int(1,43200)?
  server_id: int(1,)?
  log_level: list(off|fatal|error|warning|notice|info|debug|trace|all)?
  static_results: str?

options:
  accept_eula: false
  accept_privacy: false
