---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python
  amd64: ghcr.io/home-assistant/amd64-base-python
  armhf: ghcr.io/home-assistant/armhf-base-python
  armv7: ghcr.io/home-assistant/armv7-base-python
  i386: ghcr.io/home-assistant/i386-base-python
codenotary:
  base_image: notary@home-assistant.io
args:
  CLI_VERSION: 4.36.0
  LIBWEBSOCKETS_VERSION: 4.3.3
  TTYD_VERSION: 1.7.7
