---
version: 9.16.3
slug: dp-ssh
name: Terminal, SSH, Python, homeassistant api permissions
description: Allow logging in remotely to Home Assistant using SSH; includes Python, homeassistant and hassio permissions
url: https://github.com/diablodale/dp-ha-addons/tree/main/dp-ssh
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
audio: true
homeassistant_api: true
hassio_api: true
hassio_role: manager
host_dbus: true
ingress: true
init: false
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  authorized_keys: []
  password: ""
  apks: []
  server:
    tcp_forwarding: false
panel_icon: mdi:console
panel_title: Terminal
ports:
  22/tcp: null
schema:
  authorized_keys:
    - str
  password: password
  apks:
    - str
  server:
    tcp_forwarding: bool
startup: services
uart: true
